version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - quebrado-volume:/var/lib/postgresql/data

volumes:
  quebrado-volume:

networks:
  default:
    name: quebrado_bank
