version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - quebrado-volume:/var/lib/postgresql/data
  quebrado_bank:
    container_name: "quebrado_bank"
    image: charliecharlie/quebrado_bank:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      MIX_ENV: prod
    env_file:
      - .env
    ports:
      - '4000:4000'

volumes:
  quebrado-volume:

networks:
  default:
    name: quebrado_bank
