name: Continous Deployment

on:
  push:
    branches: ["main"]

jobs:
  push-docker-image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: charliecharlie/quebrado_bank:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    name: Deploy new version to AWS
    runs-on: ubuntu-latest
    needs:
      - push-docker-image
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install SSH key of aws
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa-aws
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host aws
              HostName ${{ secrets.HOST }}
              User ${{ secrets.USERNAME }}
              IdentityFile ~/.ssh/id_rsa-aws
      - name: Rebuilt app container
        run: ssh aws "cd quebrado_bank; docker-compose stop quebrado_bank; docker-compose pull quebrado_bank; docker-compose up -d --force-recreate quebrado_bank; docker container exec -d quebrado_bank bin/migrate"
